# Generated by Django 2.2.3 on 2019-08-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
