# Generated by Django 2.2.3 on 2019-08-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190804_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
